<a href="https://colab.research.google.com/github/Sathishk2/Bayesian/blob/main/Bayesian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
upload = files.upload()

Saving titanic3.csv to titanic3.csv

In [ ]:
import pandas as pd
df = pd.read_csv('titanic3.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [ ]:
inputs = df.drop('Survived',axis='columns')
target = df.Survived

In [ ]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head(3)

   female  male
0       0     1
1       1     0
2       1     0

In [ ]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

   Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0

In [ ]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

   Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1

In [ ]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [ ]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head(6)

   Pclass        Age     Fare  female
0       3  22.000000   7.2500       0
1       1  38.000000  71.2833       1
2       3  26.000000   7.9250       1
3       1  35.000000  53.1000       1
4       3  35.000000   8.0500       0
5       3  29.699118   8.4583       0

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.2)

In [ ]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [ ]:
model.fit(X_train,y_train)

GaussianNB()

In [ ]:
model.score(X_test,y_test)

0.8044692737430168

In [ ]:
y_test[0:10]

142    1
305    1
228    0
807    0
211    1
298    1
484    1
792    0
542    0
697    1
Name: Survived, dtype: int64

In [ ]:
model.predict(X_test[0:10])

array([1, 1, 0, 1, 1, 0, 1, 1, 1, 1])

In [ ]:
model.predict_proba(X_test[:10])
#first number is they didn't survive.
#second number is they did survive.

array([[0.41877959, 0.58122041],
       [0.00322395, 0.99677605],
       [0.90835841, 0.09164159],
       [0.38389468, 0.61610532],
       [0.26997818, 0.73002182],
       [0.766093  , 0.233907  ],
       [0.32900777, 0.67099223],
       [0.22182194, 0.77817806],
       [0.31132106, 0.68867894],
       [0.43613571, 0.56386429]])